# Lab 0 Data Analysis

In [66]:
import sys
import numpy as np
import matplotlib.pyplot as plt
from astropy.io import fits
from scipy.stats import norm
import random as rand

## 4.1: Bias Frames

## 4.2: Dark Frames

In [107]:
# Open all the files
dark1 = fits.open('../data/dark_10series_0c_0m30s.00000001.DARK.FIT')
dark2 = fits.open('../data/dark_10series_0c_0m30s.00000002.DARK.FIT')
dark3 = fits.open('../data/dark_10series_0c_0m30s.00000003.DARK.FIT')
dark4 = fits.open('../data/dark_10series_0c_0m30s.00000004.DARK.FIT')
dark5 = fits.open('../data/dark_10series_0c_0m30s.00000005.DARK.FIT')
dark6 = fits.open('../data/dark_10series_0c_0m30s.00000006.DARK.FIT')
dark7 = fits.open('../data/dark_10series_0c_0m30s.00000007.DARK.FIT')
dark8 = fits.open('../data/dark_10series_0c_0m30s.00000008.DARK.FIT')
dark9 = fits.open('../data/dark_10series_0c_0m30s.00000009.DARK.FIT')
dark10 = fits.open('../data/dark_10series_0c_0m30s.00000010.DARK.FIT')
file_list = [dark1[0].data, dark2[0].data, dark3[0].data, dark4[0].data, 
             dark5[0].data, dark6[0].data, dark7[0].data, dark8[0].data,
             dark9[0].data, dark10[0].data]


# Make master median frame
master_dark = np.zeros(shape=dark1[0].shape)     # Blank array with same shape as others
for i in range(1024):
    for j in range(1024):
        total = 0
        for dark in file_list:
            total += dark[i][j]
        master_dark[i][j] = total/10
    if i%128 == 0: print(i)
print(master_dark)


# Close all the files
dark1.close()
dark2.close()
dark3.close()
dark4.close()
dark5.close()
dark6.close()
dark7.close()
dark8.close()
dark9.close()
dark10.close()

0
128
256
384
512
640
768
896
[[1049.7 1041.  1044.2 ... 1018.2 1010.3 1012.6]
 [1060.9 1036.8 1040.2 ... 1017.8 1131.6 1014.1]
 [1054.2 1044.9 1036.4 ... 1011.5 1019.6 1037.7]
 ...
 [1039.3 1033.  1032.4 ... 1018.4 1028.2 1019.6]
 [1035.2 1033.3 1039.  ... 1023.  1022.6 1023.9]
 [1037.7 1035.7 1039.  ... 1027.6 1021.  1025.8]]


## 4.3: Imaging Flat Fields

## 4.4: Bad Pixel Map

## 4.6: Calibration Strategies